flags: {}
packages:
- .
extra-deps:
- ansi-terminal-0.9
- ansi-wl-pprint-0.6.8.2
- async-2.2.1
- call-stack-0.1.0
- clock-0.7.2
- colour-2.3.4
- hashable-1.2.7.0
- haskeline-0.7.5.0
- mtl-2.2.2
- optparse-applicative-0.14.3.0
- stm-2.5.0.0
- tagged-0.8.6
- tasty-1.2.1
- tasty-hunit-0.10.0.1
- text-1.2.3.1
- transformers-compat-0.6.4
- unbounded-delays-0.1.1.0
- wcwidth-0.0.2
- split-0.2.3.3
- strings-1.1
resolver: ghc-8.0.2
