flags:
  transformers-compat:
    five: true
packages:
- .
extra-deps:
- ansi-terminal-0.9
- ansi-wl-pprint-0.6.8.2
- clock-0.7.2
- colour-2.3.4
- optparse-applicative-0.14.3.0
- tagged-0.8.6
- tasty-1.2.1
- tasty-hunit-0.10.0.1
- transformers-compat-0.6.4
- unbounded-delays-0.1.1.0
- wcwidth-0.0.2
- split-0.2.3.3
- text-1.2.3.1
resolver: ghc-8.0.2
